# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bab2ed0a351a64d69d0bb876d02659eaad754ebf33512da3504dc61d50c8af14014108f152189fedfa037e2afd8b56445790525669f4f3bff01cd43ddbe7996d

test:
  secret_key_base: 626ffb3e5967fcfb7f6ba513f5442e2cf640da97cbcdda3fc8236a907d1817e2a660d1768629190bba93796fbb3b0304bde0967cba6f4d2fbba2a5777e6589e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
